version: '3'

services:
  langaugeserver:
    image: python:3
    volumes:
      - ${PWD}:${PWD}
    ports:
      - 9190:9190
    working_dir: ${PWD}
    command: bash -c 'pip install pipenv && pipenv install --dev && pipenv run pyls --host 0.0.0.0 --port 9190 --tcp -v'
