version: '3'

services:
  template:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/project
    working_dir: /opt/project
    command: tail -f /dev/null
